#!/usr/bin/env bash
#
# Obelisk — read the five theme file formats out of the installed packages.
#
# design/generate.py has to emit a Plasma colour scheme, a Plasma look-and-feel package,
# an SDDM theme, a Plymouth theme and a GRUB theme. Every one of those formats has
# changed across major versions, and tutorials for them are mostly written against
# Plasma 5. Guessing five formats is five times the exposure of guessing one, and the
# bootmode episode already showed what a guess costs: a full build-and-test cycle to
# learn a string we could have read.
#
# So this reads the answer out of working reference implementations shipped by the same
# package versions Obelisk will target -- breeze, breeze-grub, breeze-plymouth,
# plasma-workspace, sddm -- rather than from documentation about them.
#
# It answers questions; it does not change anything. Run it in an Arch container:
#
#     docker run --rm -v "$PWD:/build" -w /build archlinux:latest \
#         bash scripts/verify-theme-formats.sh
#
# Exit status: 0 every question answered, 1 one or more unanswered, 2 environment error.

set -euo pipefail

readonly SCRIPT_NAME="${0##*/}"
REPO_ROOT="$(cd -- "$(dirname -- "$0")/.." && pwd)"
readonly REPO_ROOT

die() { printf '\n%s: error: %s\n\n' "$SCRIPT_NAME" "$1" >&2; exit 2; }

on_err() {
    local code=$? line=$1 cmd=$2
    printf '\n%s: FAILED  exit=%s line=%s cmd=%s\n\n' "$SCRIPT_NAME" "$code" "$line" "$cmd" >&2
    exit "$code"
}
trap 'on_err "$LINENO" "$BASH_COMMAND"' ERR

OUT_DIR="${1:-${REPO_ROOT}/out}"
mkdir -p -- "$OUT_DIR"
readonly REPORT="${OUT_DIR}/theme-formats.md"

UNANSWERED=()

command -v pacman >/dev/null 2>&1 || die \
"pacman not found. This must run on Arch or in an archlinux container:

    docker run --rm -v \"\$PWD:/build\" -w /build archlinux:latest \
        bash scripts/verify-theme-formats.sh"

section() { printf '\n\n## %s\n\n' "$1" | tee -a "$REPORT"; }
note()    { printf '%s\n' "$1" | tee -a "$REPORT"; }
fence()   { printf '```\n' | tee -a "$REPORT"; }

# Print a file, or record the question as unanswered and say why.
show_file() {
    local label="$1" path="$2" limit="${3:-60}"
    if [[ -f "$path" ]]; then
        note "\`${path}\`"
        fence
        head -n "$limit" -- "$path" | tee -a "$REPORT"
        fence
        return 0
    fi
    note "**NOT FOUND:** \`${path}\` — ${label} is unanswered."
    UNANSWERED+=("$label")
    return 0
}

first_match() {
    # first_match <glob...> ; prints the first existing path, or nothing
    local p
    for p in "$@"; do
        [[ -e "$p" ]] && { printf '%s' "$p"; return 0; }
    done
    return 1
}

: > "$REPORT"
{
    printf '# Obelisk — verified theme file formats\n\n'
    printf 'Read out of installed packages, not from documentation. Generated by `%s`.\n' "$SCRIPT_NAME"
    printf 'Date: %s\n' "$(date -u '+%Y-%m-%dT%H:%M:%SZ')"
} | tee -a "$REPORT"

printf '\n%s: installing reference packages\n' "$SCRIPT_NAME"
pacman -Syu --noconfirm --needed \
    breeze breeze-grub breeze-plymouth plasma-workspace sddm plymouth grub \
    ttf-ibm-plex fontconfig </dev/null >/dev/null

section "Package versions these formats were read from"
fence
pacman -Q breeze breeze-grub breeze-plymouth plasma-workspace sddm plymouth grub ttf-ibm-plex \
    | tee -a "$REPORT"
fence

# --- 1. Plasma colour scheme ------------------------------------------------
section "1. Plasma colour scheme (.colors)"
note "The group and key names changed between Plasma 5 and 6. A wrong key fails SILENTLY:"
note "the scheme loads and ignores it, which looks like a design bug rather than a config bug."
note ""
if scheme="$(first_match /usr/share/color-schemes/BreezeDark.colors /usr/share/color-schemes/BreezeLight.colors)"; then
    show_file "Plasma colour scheme" "$scheme" 200
    note ""
    note "Group names present:"
    fence
    grep -oE '^\[[^]]+\]' -- "$scheme" | sort -u | tee -a "$REPORT"
    fence
else
    note "**NOT FOUND:** no .colors file under /usr/share/color-schemes/"
    UNANSWERED+=("Plasma colour scheme")
fi

# --- 2. Look-and-feel package ----------------------------------------------
section "2. Plasma look-and-feel package layout"
note "metadata.json (Plasma 6) or metadata.desktop (Plasma 5)? A package with the wrong"
note "one is not detected at all."
note ""
lnf_root="/usr/share/plasma/look-and-feel"
if [[ -d "$lnf_root" ]]; then
    note "Packages installed:"
    fence
    ls -1 "$lnf_root" | tee -a "$REPORT"
    fence
    lnf="$(find "$lnf_root" -maxdepth 1 -mindepth 1 -type d | head -n1)"
    note ""
    note "Tree of \`${lnf}\`:"
    fence
    find "$lnf" -maxdepth 3 | sed "s|^${lnf}|.|" | sort | head -n 40 | tee -a "$REPORT"
    fence
    if meta="$(first_match "${lnf}/metadata.json" "${lnf}/metadata.desktop")"; then
        show_file "look-and-feel metadata" "$meta" 60
    else
        note "**NOT FOUND:** neither metadata.json nor metadata.desktop in ${lnf}"
        UNANSWERED+=("look-and-feel metadata")
    fi
else
    note "**NOT FOUND:** ${lnf_root} does not exist"
    UNANSWERED+=("look-and-feel layout")
fi

# --- 3. SDDM theme ----------------------------------------------------------
section "3. SDDM theme metadata and QML imports"
note "A theme that fails to load leaves a black screen with no greeter, which is"
note "indistinguishable from a broken boot."
note ""
sddm_root="/usr/share/sddm/themes"
if [[ -d "$sddm_root" ]]; then
    note "Themes installed:"
    fence
    ls -1 "$sddm_root" | tee -a "$REPORT"
    fence
    theme="$(find "$sddm_root" -maxdepth 1 -mindepth 1 -type d | head -n1)"
    if [[ -n "$theme" ]]; then
        for f in metadata.desktop theme.conf; do
            [[ -f "${theme}/${f}" ]] && show_file "SDDM ${f}" "${theme}/${f}" 40
        done
        note ""
        note "QML import statements used by the shipped theme:"
        fence
        grep -rhoE '^import [A-Za-z0-9._]+( [0-9.]+)?' "$theme" 2>/dev/null | sort -u \
            | tee -a "$REPORT" || note "(no QML files in this theme)"
        fence
    else
        note "**NOT FOUND:** no theme directory under ${sddm_root}"
        UNANSWERED+=("SDDM theme")
    fi
else
    note "**NOT FOUND:** ${sddm_root} does not exist"
    UNANSWERED+=("SDDM theme")
fi

# --- 4. Plymouth theme ------------------------------------------------------
section "4. Plymouth theme (.plymouth)"
note "breeze-plymouth is a working reference for the key names and the module choice."
note ""
ply_root="/usr/share/plymouth/themes"
if [[ -d "$ply_root" ]]; then
    note "Themes installed:"
    fence
    ls -1 "$ply_root" | tee -a "$REPORT"
    fence
    while IFS= read -r f; do
        show_file "Plymouth theme" "$f" 40
    done < <(find "$ply_root" -name '*.plymouth' | sort | head -n 3)
    note ""
    note "Available Plymouth modules (the ScriptFile/ModuleName choices):"
    fence
    find /usr/lib/plymouth -maxdepth 1 -name '*.so' -printf '%f\n' 2>/dev/null | sort \
        | tee -a "$REPORT"
    fence
else
    note "**NOT FOUND:** ${ply_root} does not exist"
    UNANSWERED+=("Plymouth theme")
fi

# --- 5. GRUB theme ----------------------------------------------------------
section "5. GRUB theme.txt"
note "breeze-grub ships a working theme.txt for the same GRUB version we build against."
note ""
if grub_theme="$(first_match /usr/share/grub/themes/breeze/theme.txt)"; then
    show_file "GRUB theme.txt" "$grub_theme" 120
    note ""
    note "Files alongside it (fonts and assets a theme needs):"
    fence
    find "$(dirname "$grub_theme")" -maxdepth 1 -printf '%f  %s bytes\n' | sort | tee -a "$REPORT"
    fence
else
    note "Searching for any installed GRUB theme:"
    fence
    find /usr/share/grub -name 'theme.txt' 2>/dev/null | tee -a "$REPORT" || true
    fence
    found="$(find /usr/share/grub -name 'theme.txt' 2>/dev/null | head -n1)"
    if [[ -n "$found" ]]; then
        show_file "GRUB theme.txt" "$found" 120
    else
        note "**NOT FOUND:** no theme.txt anywhere under /usr/share/grub"
        UNANSWERED+=("GRUB theme.txt")
    fi
fi
note ""
note "GRUB modules available for theming (gfxterm needs these):"
fence
find /usr/lib/grub -maxdepth 2 -name 'gfxterm*.mod' -o -maxdepth 2 -name 'png.mod' \
    -o -maxdepth 2 -name 'gfxmenu.mod' 2>/dev/null | sort | tee -a "$REPORT" || true
fence

# --- 6. fontconfig family names --------------------------------------------
section "6. fontconfig family names for IBM Plex"
note "tokens.yaml names the families. A wrong string means silent fallback to some other"
note "Arabic font on every surface, which looks like a rendering bug, not a config error."
note ""
if command -v fc-list >/dev/null 2>&1; then
    note "Exact family names as fontconfig registers them:"
    fence
    fc-list : family | tr ',' '\n' | grep -i 'plex' | sort -u | tee -a "$REPORT"
    fence
    note ""
    note "What fontconfig actually resolves our token strings to:"
    fence
    for want in "IBM Plex Sans" "IBM Plex Sans Arabic" "IBM Plex Mono"; do
        printf '%-24s -> %s\n' "$want" "$(fc-match "$want" family 2>/dev/null || echo '?')" \
            | tee -a "$REPORT"
    done
    fence
else
    note "**NOT FOUND:** fc-list is unavailable"
    UNANSWERED+=("fontconfig family names")
fi

# --- summary ----------------------------------------------------------------
section "Summary"
if [[ ${#UNANSWERED[@]} -eq 0 ]]; then
    note "All six questions answered. Formats above are read from installed packages."
    printf '\n%s: all questions answered; report at %s\n' "$SCRIPT_NAME" "$REPORT"
    exit 0
fi
note "**UNANSWERED (${#UNANSWERED[@]}):**"
for q in "${UNANSWERED[@]}"; do note "- ${q}"; done
note ""
note "Do not write a generator for an unanswered format. Find the answer first."
printf '\n%s: %d question(s) unanswered; report at %s\n' "$SCRIPT_NAME" "${#UNANSWERED[@]}" "$REPORT" >&2
exit 1
